services:
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    env_file:
      - ./.env

volumes:
  postgres_data: