services:
  backend:
    build: .
    depends_on:
      - db
    ports:
      - 8000:8000
    env_file:
      - ./.env

  db:
    image: postgres:17-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    env_file:
      - ./.env
    ports:
      - 5432:5432

volumes:
  postgres_data: