# Generated by Django 5.2.5 on 2025-08-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_review_head_comment_alter_product_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images"),
        ),
    ]
